name: mentra_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: ^3.10.0
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_blue_plus: ^2.0.2
  permission_handler: ^11.0.0
  flutter_riverpod: ^3.0.3
  http: ^1.6.0
  web_socket_channel: ^3.0.3
  supabase_flutter: ^2.10.3
  google_sign_in: ^7.2.0
  dio: ^5.9.0
  flutter_dotenv: ^5.1.0
  flutter_screenutil: ^5.9.3
  go_router: ^17.0.1
  hooks_riverpod: ^3.0.3
  percent_indicator: ^4.2.5
  riverpod: ^3.0.3
  shared_preferences: ^2.5.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  generate: true
  uses-material-design: true
  assets:
   - assets/
    
  fonts:
    - family: googlesans
      fonts:
        - asset: assets/fonts/googlesans/GoogleSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/googlesans/GoogleSans-Regular.ttf
          weight: 500


    - family: gothic
      fonts:
        - asset: assets/fonts/gothic/ScienceGothic_Expanded-Regular.ttf
          weight: 500
        - asset: assets/fonts/gothic/ScienceGothic_Condensed-Bold.ttf
          weight: 700